<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SmartLayoutSwitcher.Core\SmartLayoutSwitcher.Core.csproj" />
    <ProjectReference Include="..\SmartLayoutSwitcher.Native\SmartLayoutSwitcher.Native.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseSystemDrawing>true</UseSystemDrawing>
    <ApplicationIcon>..\..\assets\branding\smart-layout-switcher.ico</ApplicationIcon>
    <Version>1.0.11</Version>
    <InformationalVersion>1.0.11</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\assets\branding\smart-layout-switcher.ico">
      <LogicalName>SmartLayoutSwitcher.App.Resources.LangIcon.ico</LogicalName>
    </EmbeddedResource>
    <Resource Include="..\..\assets\branding\smart-layout-switcher.ico">
      <Link>Resources\Lang-icon.ico</Link>
    </Resource>
  </ItemGroup>

</Project>
